package cz.datalite.zk.components.list;

public class DLListboxProfile {

	/** profile id - usually generated by persistent storage */
	private Long id;
	
	/** identifier (e.q. session name) of listbox */ 
	private String dlListboxId;

	/** profile name - shown in lovbox */
	private String name;

	/** profile will be visible only for owner and invisible for other users if set to true */
	private boolean publicProfile = true;

	/** default profile for listbox */
	private boolean defaultProfile = false;

	/** hidden profile - invisible for user */
	private boolean hidden = false;
	
	/** profile can be overwritten using save button in profile manager */
	private boolean editable = true;

	/** profile ownew */
	private String user;

	/** column model settings serialized to json */
	private String columnModelJsonData;

	/** filter model settings serialized to json */
	private String filterModelJsonData;

	/** hash code of listbox columns in time of saving profile */
	private Integer columnsHashCode;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDlListboxId() {
		return dlListboxId;
	}

	public void setDlListboxId(String dlListboxId) {
		this.dlListboxId = dlListboxId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isPublicProfile() {
		return publicProfile;
	}

	public void setPublicProfile(boolean publicProfile) {
		this.publicProfile = publicProfile;
	}
	
	public boolean isDefaultProfile() {
		return defaultProfile;
	}

	public void setDefaultProfile(boolean defaultProfile) {
		this.defaultProfile = defaultProfile;
	}

	public boolean isHidden() {
		return hidden;
	}

	public void setHidden(boolean hidden) {
		this.hidden = hidden;
	}

	public boolean isEditable() {
		return editable;
	}

	public void setEditable(boolean editable) {
		this.editable = editable;
	}

	public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getColumnModelJsonData() {
		return columnModelJsonData;
	}

	public void setColumnModelJsonData(String columnModelJsonData) {
		this.columnModelJsonData = columnModelJsonData;
	}

	public String getFilterModelJsonData() {
		return filterModelJsonData;
	}

	public void setFilterModelJsonData(String filterModelJsonData) {
		this.filterModelJsonData = filterModelJsonData;
	}

	public Integer getColumnsHashCode() {
		return columnsHashCode;
	}

	public void setColumnsHashCode(Integer columnsHashCode) {
		this.columnsHashCode = columnsHashCode;
	}

	@Override
	public String toString() {
		return "DLListboxProfile [id=" + id + ", dlListboxId=" + dlListboxId + ", name=" + name + ", publicProfile="
				+ publicProfile + ", defaultProfile=" + defaultProfile + ", hidden=" + hidden + ", user=" + user
				+ ", columnModelJsonData=" + columnModelJsonData + ", filterModelJsonData=" + filterModelJsonData
				+ ", columnsHashCode=" + columnsHashCode + "]";
	}	
}
